export const ADMIN_INJURIES_REQUEST = 'ADMIN_INJURIES_REQUEST'
export const ADMIN_INJURIES_SUCCESS = 'ADMIN_INJURIES_SUCCESS'
export const ADMIN_INJURIES_FAIL = 'ADMIN_INJURIES_FAIL'

export const NEW_INJURY_REQUEST = 'NEW_INJURY_REQUEST'
export const NEW_INJURY_SUCCESS = 'NEW_INJURY_SUCCESS'
export const NEW_INJURY_RESET = 'NEW_INJURY_RESET'
export const NEW_INJURY_FAIL = 'NEW_INJURY_FAIL'

export const UPDATE_INJURY_REQUEST = 'UPDATE_INJURY_REQUEST'
export const UPDATE_INJURY_SUCCESS = 'UPDATE_INJURY_SUCCESS'
export const UPDATE_INJURY_RESET = 'UPDATE_INJURY_RESET'
export const UPDATE_INJURY_FAIL = 'UPDATE_INJURY_FAIL'

export const INJURY_DETAILS_REQUEST = 'INJURY_DETAILS_REQUEST'
export const INJURY_DETAILS_SUCCESS = 'INJURY_DETAILS_SUCCESS'
export const INJURY_DETAILS_FAIL = 'INJURY_DETAILS_FAIL'

export const DELETE_INJURY_REQUEST = 'DELETE_INJURY_REQUEST'
export const DELETE_INJURY_SUCCESS = 'DELETE_INJURY_SUCCESS'
export const DELETE_INJURY_RESET = 'DELETE_INJURY_RESET'
export const DELETE_INJURY_FAIL = 'DELETE_INJURY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'