export const ALL_RESCUES_REQUEST = 'ALL_RESCUES_REQUEST'
export const ALL_RESCUES_SUCCESS = 'ALL_RESCUES_SUCCESS'
export const ALL_RESCUES_FAIL = 'ALL_RESCUES_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const RESCUE_DETAIL_REQUEST = 'RESCUE_DETAIL_REQUEST' 
export const RESCUE_DETAIL_SUCCESS = 'RESCUE_DETAIL_SUCCESS'
export const RESCUE_DETAIL_FAIL = 'RESCUE_DETAIL_FAIL'

export const RESCUE_DETAILS_REQUEST = 'RESCUE_DETAILS_REQUEST' 
export const RESCUE_DETAILS_SUCCESS = 'RESCUE_DETAILS_SUCCESS'
export const RESCUE_DETAILS_FAIL = 'RESCUE_DETAILS_FAIL'

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_RESET = 'NEW_COMMENT_RESET'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'

export const ADMIN_RESCUES_REQUEST = 'ADMIN_RESCUES_REQUEST'
export const ADMIN_RESCUES_SUCCESS = 'ADMIN_RESCUES_SUCCESS'
export const ADMIN_RESCUES_FAIL = 'ADMIN_RESCUES_FAIL'

export const NEW_RESCUE_REQUEST = 'NEW_RESCUE_REQUEST'
export const NEW_RESCUE_SUCCESS = 'NEW_RESCUE_SUCCESS'
export const NEW_RESCUE_RESET = 'NEW_RESCUE_RESET'
export const NEW_RESCUE_FAIL = 'NEW_RESCUE_FAIL'

export const UPDATE_RESCUE_REQUEST = 'UPDATE_RESCUE_REQUEST'
export const UPDATE_RESCUE_SUCCESS = 'UPDATE_RESCUE_SUCCESS'
export const UPDATE_RESCUE_RESET = 'UPDATE_RESCUE_RESET'
export const UPDATE_RESCUE_FAIL = 'UPDATE_RESCUE_FAIL'

export const DELETE_RESCUE_REQUEST = 'DELETE_RESCUE_REQUEST'
export const DELETE_RESCUE_SUCCESS = 'DELETE_RESCUE_SUCCESS'
export const DELETE_RESCUE_RESET = 'DELETE_RESCUE_RESET'
export const DELETE_RESCUE_FAIL = 'DELETE_RESCUE_FAIL'

export const ADOPT_RESCUE_REQUEST = 'ADOPT_RESCUE_REQUEST'
export const ADOPT_RESCUE_SUCCESS = 'ADOPT_RESCUE_SUCCESS'
export const ADOPT_RESCUE_RESET = 'ADOPT_RESCUE_RESET'
export const ADOPT_RESCUE_FAIL = 'ADOPT_RESCUE_FAIL'

export const ADMIN_REQUESTS_REQUEST = 'ADMIN_REQUESTS_REQUEST'
export const ADMIN_REQUESTS_SUCCESS = 'ADMIN_REQUESTS_SUCCESS'
export const ADMIN_REQUESTS_FAIL = 'ADMIN_REQUESTS_FAIL'

export const APPROVE_REQUEST_REQUEST = 'APPROVE_REQUEST_REQUEST'
export const APPROVE_REQUEST_SUCCESS = 'APPROVE_REQUEST_SUCCESS'
export const APPROVE_REQUEST_RESET = 'APPROVE_REQUEST_RESET'
export const APPROVE_REQUEST_FAIL = 'APPROVE_REQUEST_FAIL'

export const DENY_REQUEST_REQUEST = 'DENY_REQUEST_REQUEST'
export const DENY_REQUEST_SUCCESS = 'DENY_REQUEST_SUCCESS'
export const DENY_REQUEST_RESET = 'DENY_REQUEST_RESET'
export const DENY_REQUEST_FAIL = 'DENY_REQUEST_FAIL'

export const ADOPTER_ADOPTED_REQUEST = 'ADOPTER_ADOPTED_REQUEST'
export const ADOPTER_ADOPTED_SUCCESS = 'ADOPTER_ADOPTED_SUCCESS'
export const ADOPTER_ADOPTED_FAIL = 'ADOPTER_ADOPTED_FAIL'

export const TREAT_RESCUE_REQUEST = 'TREAT_RESCUE_REQUEST'
export const TREAT_RESCUE_SUCCESS = 'TREAT_RESCUE_SUCCESS'
export const TREAT_RESCUE_RESET = 'TREAT_RESCUE_RESET'
export const TREAT_RESCUE_FAIL = 'TREAT_RESCUE_FAIL'

export const GET_RESCUEDCHART_REQUEST = 'GET_RESCUEDCHART_REQUEST'
export const GET_RESCUEDCHART_SUCCESS = 'GET_RESCUEDCHART_SUCCESS'
export const GET_RESCUEDCHART_FAIL = 'GET_RESCUEDCHART_FAIL'

export const GET_ADOPTEDCHART_REQUEST = 'GET_ADOPTEDCHART_REQUEST'
export const GET_ADOPTEDCHART_SUCCESS = 'GET_ADOPTEDCHART_SUCCESS'
export const GET_ADOPTEDCHART_FAIL = 'GET_ADOPTEDCHART_FAIL'